INSERT INTO reviews (rating, message, game_id, user_id)
VALUES
('4', 'Great game. Would play again!', 1, 1),
('5', 'Cannot put this one down. Excited to see what else this game has in store for me', 1, 2),
('3', 'The open-world design is impressive, offering countless hours of exploration. However, the main quests can feel a bit linear.', 1, 3),
('2', 'The graphics are stunning, but the gameplay feels repetitive after a few hours. A decent choice for casual gamers.', 1, 4),
('4', 'The story is captivating and filled with twists, but the controls can be a bit clunky. Overall, a solid adventure.', 1, 5),
('4', 'An excellent soundtrack complements the immersive world. Some minor bugs slightly detract from the experience.', 2, 1),
('5', 'Character customization options are vast, allowing for a personalized experience. Combat mechanics could use some refinement.', 2, 2),
('3', 'Multiplayer mode is highly engaging, keeping players hooked for hours. The single-player campaign feels a bit short.', 2, 3),
('2', 'The game''s unique art style sets it apart from other titles. Difficulty spikes can be frustrating for newcomers.', 2, 4),
('4', 'Dialogue choices significantly impact the storyline, adding replay value. Some side quests feel like filler content.', 2, 5),
('4', 'Boss battles are challenging and rewarding. The save system can be unforgiving at times.', 3, 1),
('5', 'The narrative is well-written and emotionally charged. Load times are longer than expected.', 3, 2),
('3', 'Crafting systems are deep and complex, enhancing the survival aspect. Early game pacing is a bit slow.', 3, 3),
('2', 'Online co-op is seamless and fun with friends. Solo play lacks the same level of excitement.', 3, 4),
('4', 'Visual effects are top-notch, making each encounter feel epic. The HUD can be cluttered and overwhelming.', 3, 5),
('4', 'Voice acting is superb, bringing characters to life. AI companions can be unpredictable.', 4, 1),
('5', 'The world-building is rich with lore and history. Some mechanics feel outdated and clunky.', 4, 2),
('3', 'The game offers a refreshing take on its genre with innovative mechanics. Some technical issues need to be patched.', 4, 3),
('2', 'The storyline is engaging with well-developed characters. Side missions can be repetitive.', 4, 4),
('4', 'Stunning visuals and a haunting soundtrack create a memorable atmosphere. Combat can feel a bit unbalanced.', 4, 5),
('4', 'Exploration is rewarding with hidden secrets around every corner. The main questline is relatively short.', 5, 1),
('5', 'The game offers a perfect blend of action and strategy. However, it can be quite demanding on lower-end systems.', 5, 2),
('3', 'Customizable skills and abilities add depth to gameplay. Story pacing is inconsistent.', 5, 3),
('2', 'The game''s physics engine is impressive, adding realism to the experience. Some animations are stiff and unnatural.', 5, 4),
('4', 'The multiplayer community is active and welcoming. Frequent updates keep the game fresh.', 5, 5),
('4', 'The story-driven campaign is emotionally gripping. Some technical hiccups need to be addressed.', 6, 1),
('5', 'Environmental storytelling is done exceptionally well. The difficulty curve is steep for beginners.', 6, 2),
('3', 'The soundtrack enhances the immersive experience. The inventory system could use better organization.', 6, 3),
('2', 'Unique gameplay mechanics set this title apart from others. Visual bugs can occasionally break immersion.', 6, 4),
('4', 'The game world is beautifully crafted and expansive. NPC interactions can be repetitive.', 6, 5),
('4', 'A strong emphasis on player choice adds depth to the narrative. Load times are longer than expected.', 7, 1),
('5', 'Innovative puzzle design keeps the gameplay engaging. The plot can be predictable at times.', 7, 2),
('3', 'The game''s atmosphere is eerie and captivating. Controls can feel unresponsive in critical moments.', 7, 3),
('2', 'Dynamic weather effects add a layer of realism. Character models sometimes lack detail.', 7, 4),
('4', 'The combat system is intuitive and fluid. Side quests often lack variety.', 7, 5),
('4', 'An intriguing plot keeps players invested from start to finish. Some voice lines are poorly delivered.', 8, 1),
('5', 'Beautifully crafted environments invite exploration. The ending feels rushed.', 8, 2),
('3', 'A rich and detailed lore enhances the story. Technical glitches can be distracting.', 8, 3),
('2', 'The game''s humor is well-executed and adds charm. Some levels are unnecessarily difficult.', 8, 4),
('4', 'Sound design is excellent, creating an immersive experience. The game''s length is shorter than expected.', 8, 5),
('4', 'The crafting system is intuitive and satisfying. Enemy AI can be inconsistent.', 9, 1),
('5', 'A diverse cast of characters keeps the narrative interesting. The user interface is not very intuitive.', 9, 2),
('3', 'The game offers a perfect blend of action and story. Some graphical issues need to be addressed.', 9, 3),
('2', 'The multiplayer mode is highly competitive and thrilling. Single-player content feels lacking.', 9, 4),
('4', 'A compelling story with multiple endings adds replay value. Gameplay mechanics can feel outdated.', 9, 5),
('4', 'The world feels alive with dynamic events and activities. Combat can become repetitive over time.', 10, 1),
('5', 'Gorgeous visuals and a haunting score make for an immersive experience. Some gameplay elements feel underdeveloped.', 10, 2),
('3', 'The game offers a deep and engaging storyline. Minor bugs occasionally disrupt gameplay.', 10, 3),
('2', 'The art style is unique and visually appealing. Difficulty spikes can be frustrating.', 10, 4),
('4', 'The game''s soundtrack is both memorable and fitting. Some missions feel like filler content.', 10, 5),
('4', 'The narrative is well-crafted with interesting plot twists. The game can be quite buggy at launch.', 11, 1),
('5', 'Engaging gameplay mechanics keep the action fresh. The story could be more original.', 11, 2),
('3', 'The open world is vast and full of secrets. Side quests can become monotonous.', 11, 3),
('2', 'The game''s voice acting is top-notch. Some textures can be low resolution.', 11, 4),
('4', 'Customization options add a personal touch to the experience. The tutorial is lacking in detail.', 11, 5),
('4', 'Multiplayer matches are intense and strategic. The matchmaking system needs improvement.', 12, 1),
('5', 'The storyline is gripping and full of surprises. Load times can be excessive.', 12, 2),
('3', 'Beautifully designed levels encourage exploration. The game can be quite difficult for newcomers.', 12, 3),
('2', 'The game''s atmosphere is dark and immersive. Combat mechanics can feel clunky.', 12, 4),
('4', 'The plot is engaging with well-written characters. Some technical issues mar the experience.', 12, 5),
('4', 'An innovative gameplay mechanic sets this game apart. The graphics could use an upgrade.', 13, 1),
('5', 'The game''s humor and wit are standout features. Some levels are overly challenging.', 13, 2),
('3', 'A rich narrative and complex characters drive the story. The ending leaves much to be desired.', 13, 3),
('2', 'The combat system is rewarding and skill-based. Visual glitches can be distracting.', 13, 4),
('4', 'An engaging story with meaningful choices. The game is prone to occasional crashes.', 13, 5),
('4', 'The world-building is extensive and detailed. Some quests feel like padding.', 14, 1),
('5', 'Beautiful visuals and a compelling soundtrack. The controls can be awkward at times.', 14, 2),
('3', 'The story is immersive with well-paced twists. Combat can become repetitive after a while."', 14, 3),
('2', 'Exploration is highly rewarding with plenty of secrets to find. Some gameplay mechanics feel outdated.', 14, 4),
('4', 'A gripping narrative keeps players engaged. Technical issues occasionally hinder the experience.', 15, 1),
('4', 'The game''s art style is unique and charming. Difficulty spikes can be frustrating.', 15, 2),
('5', 'The multiplayer component is highly enjoyable. The single-player campaign lacks depth.', 15, 3),
('3', 'The storyline is rich with lore and detail. Some gameplay elements are unpolished.', 15, 4),
('2', 'The game offers a perfect balance of action and exploration. Minor bugs can be annoying.', 15, 5),
('4', 'The soundtrack enhances the overall atmosphere. Some controls feel unresponsive.', 16, 1),
('4', 'A diverse and interesting cast of characters. The game suffers from occasional frame rate drops.', 16, 2),
('5', 'Innovative mechanics keep the gameplay fresh. The plot can be predictable at times.', 16, 3),
('3', 'The open world is beautifully crafted and engaging. Side missions often feel repetitive.', 16, 4),
('2', 'The game''s humor adds a unique charm. Certain levels are overly difficult.', 16, 5),
('4', 'A deep and engaging narrative. Technical glitches can be frustrating.', 17, 1),
('4', 'The art style is visually stunning. Some gameplay mechanics are not well-explained.', 17, 2),
('5', 'The multiplayer mode is thrilling and competitive. Single-player content feels sparse.', 17, 3),
('3', 'The story is well-written and captivating. Load times are longer than expected.', 17, 4),
('2', 'Beautifully designed environments invite exploration. Some voice acting is subpar.', 17, 5),
('4', 'A strong emphasis on player choice adds depth. The game can be buggy at times.', 18, 1),
('4', 'The game''s soundtrack is memorable and fitting. Some missions feel like filler.', 18, 2),
('5', 'The combat system is intuitive and engaging. The story could be more original.', 18, 3),
('3', 'The world feels alive with dynamic events. Combat can become repetitive over time.', 18, 4),
('2', 'Gorgeous visuals and a haunting score. Some gameplay elements feel underdeveloped.', 18, 5),
('4', 'A deep and engaging storyline. Minor bugs occasionally disrupt gameplay.', 19, 1),
('4', 'The art style is unique and appealing. Difficulty spikes can be frustrating.', 19, 2),
('5', 'The game''s humor is well-executed. Some levels are overly challenging.', 19, 3),
('3', 'A rich narrative with complex characters. The ending leaves much to be desired.', 19, 4),
('2', 'The combat system is rewarding and skill-based. Visual glitches can be distracting.', 19, 5),
('4', 'An engaging story with meaningful choices. The game is prone to occasional crashes.', 20, 1),
('4', 'Extensive and detailed world-building. Some quests feel like padding.', 20, 2),
('5', 'Beautiful visuals and a compelling soundtrack. The controls can be awkward.', 20, 3),
('3', 'Immersive story with well-paced twists. Combat can become repetitive.', 20, 4),
('2', 'A gripping narrative keeps players engaged. Technical issues occasionally hinder the experience.', 20, 5),
('4', 'Unique and charming art style. Difficulty spikes can be frustrating.', 21, 1),
('4', 'Highly enjoyable multiplayer component. Single-player campaign lacks depth.', 21, 2),
('5', 'The game offers a refreshing take on its genre with innovative mechanics. Some technical issues need to be patched.', 21, 3),
('3', 'The storyline is engaging with well-developed characters. Side missions can be repetitive.', 21, 4),
('2', 'Stunning visuals and a haunting soundtrack create a memorable atmosphere. Combat can feel a bit unbalanced.', 21, 5),
('4', 'Exploration is rewarding with hidden secrets around every corner. The main questline is relatively short.', 22, 1),
('4', 'The game offers a perfect blend of action and strategy. However, it can be quite demanding on lower-end systems.', 22, 2),
('5', 'Customizable skills and abilities add depth to gameplay. Story pacing is inconsistent.', 22, 3),
('3', 'The game''s physics engine is impressive, adding realism to the experience. Some animations are stiff and unnatural.', 22, 4),
('2', 'The multiplayer community is active and welcoming. Frequent updates keep the game fresh.', 22, 5),
('4', 'The story-driven campaign is emotionally gripping. Some technical hiccups need to be addressed.', 23, 1),
('4', 'Environmental storytelling is done exceptionally well. The difficulty curve is steep for beginners.', 23, 2),
('5', 'The soundtrack enhances the immersive experience. The inventory system could use better organization.', 23, 3),
('3', 'Unique gameplay mechanics set this title apart from others. Visual bugs can occasionally break immersion.', 23, 4),
('2', 'The game world is beautifully crafted and expansive. NPC interactions can be repetitive.', 23, 5),
('4', 'A strong emphasis on player choice adds depth to the narrative. Load times are longer than expected.', 24, 1),
('4', 'Innovative puzzle design keeps the gameplay engaging. The plot can be predictable at times.', 24, 2),
('5', 'The game''s atmosphere is eerie and captivating. Controls can feel unresponsive in critical moments.', 24, 3),
('3', 'The story is well-written and captivating. Load times are longer than expected.', 24, 4),
('2', 'Beautifully designed environments invite exploration. Some voice acting is subpar.', 24, 5),
('4', 'A strong emphasis on player choice adds depth. The game can be buggy at times.', 25, 1),
('4', 'The game''s soundtrack is memorable and fitting. Some missions feel like filler.', 25, 2),
('5', 'The combat system is intuitive and engaging. The story could be more original.', 25, 3),
('3', 'The world feels alive with dynamic events. Combat can become repetitive over time.', 25, 4),
('2', 'Gorgeous visuals and a haunting score. Some gameplay elements feel underdeveloped.', 25, 5),
('4', 'A deep and engaging storyline. Minor bugs occasionally disrupt gameplay.', 26, 1),
('4', 'The art style is unique and appealing. Difficulty spikes can be frustrating.', 26, 2),
('5', 'The game''s humor is well-executed. Some levels are overly challenging.', 26, 3),
('3', 'A rich narrative with complex characters. The ending leaves much to be desired.', 26, 4),
('2', 'The combat system is rewarding and skill-based. Visual glitches can be distracting.', 26, 5),
('4', 'An engaging story with meaningful choices. The game is prone to occasional crashes.', 27, 1),
('4', 'Extensive and detailed world-building. Some quests feel like padding.', 27, 2),
('5', 'Beautiful visuals and a compelling soundtrack. The controls can be awkward.', 27, 3),
('3', 'Immersive story with well-paced twists. Combat can become repetitive.', 27, 4),
('2', 'A gripping narrative keeps players engaged. Technical issues occasionally hinder the experience.', 27, 5)