INSERT INTO games (name, description, store_url, trailer_url, controller_support, is_on_sale, language_id, genre_id, system_id)
VALUES
('The Legend Of Zelda: Breathe of the Wild', 'The Legend of Zelda: Breath of the Wild is a 2017 action-adventure game developed and published by Nintendo for the Nintendo Switch and Wii U. Set at the end of the Zelda timeline, the player controls an amnesiac Link as he sets out to save Princess Zelda and prevent Calamity Ganon from destroying the world.', 'https://www.bestbuy.ca/en-ca/product/the-legend-of-zelda-breath-of-the-wild-switch/10440780', 'https://www.youtube.com/embed/1rPxiXXxftE?si=Wrj55ogM1lh41JY3', true, false, 1, 1, 1),
('Hogwarts Legacy', 'Hogwarts Legacy is an action role-playing game played from a third-person perspective. It is set at Hogwarts School of Witchcraft and Wizardry and its surrounding areas, influenced by the Wizarding World franchise.', 'https://www.bestbuy.ca/en-ca/product/hogwarts-legacy-xbox-one/16016423?icmp=Recos_3across_tp_sllng_prdcts_plp&referrer=PLP+Top+Seller', 'https://www.youtube.com/embed/BtyBjOW8sGY?si=Mtw4dUkMyUi0RAn_', true, false, 1, 1, 2),
('Soulmask', 'Escaping a deadly sacrificial ritual, you find an ancient mystical mask on your journey. This mask holds potent knowledge, changing the world you knew. Face the harsh challenges of nature, survive, rally followers, and build your own tribe. Explore and unveil the truths behind the enigmatic mask.', 'https://store.steampowered.com/app/2646460/Soulmask/?curator_clanid=4777282', 'https://www.youtube.com/embed/PuaFdvysulU?si=pErFAm-_cBP7JOyE', false, false, 1, 1, 4),
('Call Of Duty: Modern Warfare III', 'In the direct sequel to the record-breaking Call of Duty®: Modern Warfare® II, Captain Price and Task Force 141 face off against the ultimate threat.', 'https://store.steampowered.com/app/1938090/Call_of_Duty/', 'https://www.youtube.com/embed/mHDEDDrGYvo?si=izbJSBd2tC4ZcbqX', true, true, 1, 3, 4),
('Counter Strike 2', 'For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.', 'https://store.steampowered.com/app/730/CounterStrike_2/?curator_clanid=4777282', 'https://www.youtube.com/embed/c80dVYcL69E?si=zBfBDXhbFi1PdBrn', true, false, 1, 3, 4),
('F1 2024', 'Join the grid and Be One of the 20. Drive like the Greatest in EA SPORTS™ F1® 24, the official video game of the 2024 FIA Formula One World Championship™.', 'https://store.steampowered.com/app/2488620/F1_24/?curator_clanid=4777282', 'https://www.youtube.com/embed/NnyCWsA6KSI?si=BWVmsnqNLYNlNM1_', true, false, 1, 4, 3),
('Destiny 2', 'Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere, absolutely free.', 'https://store.steampowered.com/app/1085660/Destiny_2/?curator_clanid=4777282', 'https://www.youtube.com/embed/ZJLAJVmggt0?si=BPScFZpVc9FTeXKi', true, true, 1, 3, 3),
('Apex Legends', 'Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.', 'https://store.steampowered.com/app/1172470/Apex_Legends/?curator_clanid=4777282', 'https://www.youtube.com/embed/oQtHENM_GZU?si=z5pmxkxF8gB3QP_3', true, true, 1, 3, 4),
('Roboquest', 'Roboquest is a fast FPS Roguelite in a scorched futureworld. Youre a rebooted Guardian, ready to kick some metal ass! Fight with your buddy or by yourself and annihilate hordes of deadly bots in ever-changing environments.', 'https://store.steampowered.com/app/692890/Roboquest/?curator_clanid=4777282', 'https://www.youtube.com/embed/p-LHpH8NCNw?si=zDNfP2VF58vSWjHC', true, false, 1, 3, 4),
('Rust', 'The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.', 'https://store.steampowered.com/app/252490/Rust/?curator_clanid=4777282', 'https://www.youtube.com/embed/LGcECozNXEw?si=uyCGzOPzJ_BMX_hx', false, true, 1, 2, 4),
('DayZ', 'How long can you survive a post-apocalyptic world? A land overrun with an infected "zombie" population, where you compete with other survivors for limited resources. Will you team up with strangers and stay strong together? Or play as a lone wolf to avoid betrayal? This is DayZ – this is your story.', 'https://store.steampowered.com/app/221100/DayZ/?curator_clanid=4777282', 'https://www.youtube.com/embed/7jk8prJA9nI?si=cos5QwvQtMSm7d-_', false, false, 1, 2, 4),
('Final Fantasy XIV Online', 'Join over 27 million adventurers worldwide and take part in an epic and ever-changing FINAL FANTASY. Experience an unforgettable story, exhilarating battles, and a myriad of captivating environments to explore.', 'https://store.steampowered.com/app/39210/FINAL_FANTASY_XIV_Online/?curator_clanid=4777282', 'https://www.youtube.com/embed/zTTtd6bnhFs?si=ejFj-gsUMSRKiRNg', true, false, 1, 2, 2),
('Runescape', 'RuneScape is a high fantasy open world MMORPG. Explore an ever changing and evolving living world where new challenges, skills, and quests await. Featuring unprecedented player freedom, you choose how to play, adventure, and grow.', 'https://store.steampowered.com/app/1343400/RuneScape/?curator_clanid=4777282', 'https://www.youtube.com/embed/mXAvlbgd_-c?si=YbzNlv_6ha6XChMA', false, false, 1, 2, 4),
('Elite Dangerous', 'Take control of your own starship in a cutthroat galaxy. Elite Dangerous is the definitive massively multiplayer space epic.', 'https://store.steampowered.com/app/359320/Elite_Dangerous/?curator_clanid=4777282', 'https://www.youtube.com/embed/YESNObZJTgQ?si=OqLVa-O0wm9ZrCNe', true, false, 1, 2, 3),
('Red Dead Redemption 2', 'After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.', 'https://store.playstation.com/en-us/product/UP1004-CUSA03041_00-REDEMPTIONFULL02', 'https://www.youtube.com/embed/gmA6MrX81z4?si=Ac4Ia-kwCzr_-pZS', true, false, 1, 1, 3),
('God of War: Ragnarok', 'Join Kratos and Atreus on a mythic journey for answers before Ragnarök arrives. Together, father and son must put everything on the line as they journey to each of the Nine Realms in God of War Ragnarök, the brutal and epic sequel in the action franchise.', 'https://www.bestbuy.ca/en-ca/product/god-of-war-ragnarok-ps5/16552610?cmp=knc-s-71700000118651884&gad_source=1&gclid=CjwKCAjw34qzBhBmEiwAOUQcF-tD57wONoKst9_KJ6_f-YeXtumrIv8Bja8pNyyMyOsTJ1StAyS-XRoCzxkQAvD_BwE&gclsrc=aw.ds', 'https://www.youtube.com/embed/57JVvtyncY4?si=Jf8JoDCN9nZtiTgG', true, true, 1, 1, 2),
('Starfield', 'Starfield is a 2023 action role-playing game developed by Bethesda Game Studios and published by Bethesda Softworks. In the game, the player character joins a group of space explorers who must venture to various corners of the galaxy to acquire mysterious artifacts.', 'https://www.bestbuy.ca/en-ca/product/starfield-standard-edition-xbox-series-x/17151100?cmp=knc-s-71700000118651884&gad_source=1&gclid=CjwKCAjw34qzBhBmEiwAOUQcF9JxygK2vIdIMyCrWRxqUJajntT0qaM33fjKhC1iipEF9jHe-uI1EBoCntQQAvD_BwE&gclsrc=aw.ds', 'https://www.youtube.com/embed/kfYEiTdsyas?si=fQ8Kr8xnqrYtm19K', true, false, 1, 1, 4),
('PowerWash Simulator', 'PowerWash Simulator embraces the joys of cleaning by letting you fire jets of cleanly goodness from a high-powered, pressurized water nozzle. Clean structures, environments, and vehicles, all while managing your soap and supplies. You can also challenge yourself with time and water challenges to see how efficiently you clean under pressure.', 'https://store.steampowered.com/app/1290000/PowerWash_Simulator/', 'https://www.youtube.com/embed/k5G-2qTupCk?si=eRo2GoDH7wxNab8-', true, true, 1, 4, 4),
('Cities: Skylines', 'Cities: Skylines II improves and expands upon the robust city building mechanics fans know from the prequel, including fully realized transportation and economic systems, enhanced construction and customization options, including American and European styles, and advanced modding capabilities.', 'https://store.steampowered.com/app/949230/Cities_Skylines_II/', 'https://www.youtube.com/embed/7vlKoMi4Qr0?si=3sNetvL4R7jlNXqo', true, false, 1, 4, 3),
('Stardew Valley', 'Stardew Valley is an open-ended country-life RPG! Youve inherited your grandfathers old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?', 'https://store.steampowered.com/app/413150/Stardew_Valley/', 'https://www.youtube.com/embed/ot7uXNQskhs?si=f6OA4RtZdzbEO4Ye', true, true, 1, 4, 3),
('Farming Simulator 22', 'Agriculture, animal husbandry and forestry offer a huge variety of farming activities while you face the challenges of the four seasons, especially when winter sets in. Creatively build your own farm and extend your farming operations with production chains - forming an agricultural empire!', 'https://store.steampowered.com/app/1248130/Farming_Simulator_22/#:~:text=About%20This%20Game&text=Agriculture%2C%20animal%20husbandry%20and%20forestry,chains%20%2D%20forming%20an%20agricultural%20empire!', 'https://www.youtube.com/embed/SptqQeQsiHk?si=VB3JxRx34BWKlJfU', true, false, 1, 4, 2),
('The Sims 4', 'The Sims 4 is a social simulation game, similar to preceding titles in the series. There is no primary objective or goal to achieve, and instead of fulfilling objectives, the player is encouraged to make choices and engage fully in an interactive environment.', 'https://store.steampowered.com/app/1222670/The_Sims_4/', 'https://www.youtube.com/embed/GJENRAB4ykA?si=K2_S4wWZ1KkBR39o', false, false, 1, 4, 4),
('Baldurs Gate 3', 'Baldurs Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.', 'https://www.playstation.com/en-ca/games/baldurs-gate-3/', 'https://www.youtube.com/embed/XuCfkgaaa08?si=Y7eMg4RZZi115o00', true, false, 1, 5, 4),
('Divinity Original Sin 2', 'Divinity: Original Sin II is a role-playing video game played from an isometric perspective. As with Divinity: Original Sin, players can play alone or in cooperative multiplayer, although Original Sin II allows a party of up to four players', 'https://store.steampowered.com/app/435150/Divinity_Original_Sin_2__Definitive_Edition/', 'https://www.youtube.com/embed/bTWTFX8qzPI?si=9MA8FiLfRtB-JyOg', true, true, 1, 5, 2),
('Diablo 4', 'Diablo® IV is the ultimate action RPG experience with endless evil to slaughter, countless abilities to master, nightmarish dungeons, and legendary loot.', 'https://us.shop.battle.net/en-us/product/diablo-iv', 'https://www.youtube.com/embed/mZEzFyxKjt8?si=zkBEmEXFwsWxOfMv', true, false, 1, 5, 4),
('The Elder Scrolls: Skyrim', 'Its main story focuses on the players character, the Dragonborn, on their quest to defeat Alduin the World-Eater, a dragon who is prophesied to destroy the world.', 'https://store.steampowered.com/app/489830/The_Elder_Scrolls_V_Skyrim_Special_Edition/', 'https://www.youtube.com/embed/JSRtYpNRoN0?si=aTK7SMkMjK7mCJmL', true, false, 1, 5, 4),
('World Of Warcraft', 'In World of Warcraft, you play a powerful hero who fights towering monsters, delves perilous dungeons, defends the world of Azeroth against all threats, and much more.', 'https://worldofwarcraft.blizzard.com/en-us/start', 'https://www.youtube.com/embed/vlVSJ0AvZe0?si=ttJPrApZkEtOhrKw', false, false, 1, 5, 4)


/* ('Nintendo Switch'),
('Playstation 5'),
('Xbox One'),
('PC'),
('Mobile');
 */
