DROP TABLE IF EXISTS wishlists_games CASCADE;
CREATE TABLE wishlists_games (
  id SERIAL PRIMARY KEY NOT NULL,
  wishlist_id INTEGER REFERENCES wishlists(id) ON DELETE CASCADE,
  game_id INTEGER REFERENCES games(id) ON DELETE CASCADE
);